spring.application.name=demo
firebase.project-id=tests-7bf58
# Local development: use service account JSON added by the user.
firebase.credentials.location=file:./src/main/tests-7bf58-firebase-adminsdk-fbsvc-74a6c8f3b8.json

# Firebase web app config provided by the team.
firebase.web.api-key=AIzaSyCW6tGYEmETrnNthayc1ifeo_WYQlgu1Ew
firebase.web.auth-domain=tests-7bf58.firebaseapp.com
firebase.web.project-id=tests-7bf58
firebase.web.storage-bucket=tests-7bf58.firebasestorage.app
firebase.web.messaging-sender-id=876709401783
firebase.web.app-id=1:876709401783:web:a00f5f385dcea54b622932
firebase.web.measurement-id=G-Q8V6S6HVP7
server.error.include-message=always
